# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Fri Aug 16 15:51:46 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(920, 800)
        MainWindow.setMinimumSize(QtCore.QSize(920, 800))
        MainWindow.setMaximumSize(QtCore.QSize(920, 800))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8("XYZLRAconverter"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Icons/app_icon1.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 721))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.XYZtable = QtGui.QTableWidget(self.layoutWidget)
        self.XYZtable.setEnabled(True)
        self.XYZtable.setFrameShadow(QtGui.QFrame.Sunken)
        self.XYZtable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.XYZtable.setObjectName(_fromUtf8("XYZtable"))
        self.XYZtable.setColumnCount(3)
        self.XYZtable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.XYZtable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(2, item)
        self.XYZtable.horizontalHeader().setCascadingSectionResizes(False)
        self.XYZtable.horizontalHeader().setDefaultSectionSize(160)
        self.XYZtable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.XYZtable)
        self.LRAtable = QtGui.QTableWidget(self.layoutWidget)
        self.LRAtable.setAlternatingRowColors(True)
        self.LRAtable.setObjectName(_fromUtf8("LRAtable"))
        self.LRAtable.setColumnCount(3)
        self.LRAtable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.LRAtable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(2, item)
        self.LRAtable.horizontalHeader().setCascadingSectionResizes(False)
        self.LRAtable.horizontalHeader().setDefaultSectionSize(160)
        self.LRAtable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.LRAtable)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(570, 20, 330, 250))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.LineEditOuterDia = QtGui.QLineEdit(self.groupBox)
        self.LineEditOuterDia.setObjectName(_fromUtf8("LineEditOuterDia"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEditOuterDia)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.LineEditWallThickness = QtGui.QLineEdit(self.groupBox)
        self.LineEditWallThickness.setObjectName(_fromUtf8("LineEditWallThickness"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LineEditWallThickness)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.LineEditCLR = QtGui.QLineEdit(self.groupBox)
        self.LineEditCLR.setObjectName(_fromUtf8("LineEditCLR"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LineEditCLR)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.LineEditLength = QtGui.QLineEdit(self.groupBox)
        self.LineEditLength.setEnabled(False)
        self.LineEditLength.setObjectName(_fromUtf8("LineEditLength"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LineEditLength)
        self.horizontalLayout.addLayout(self.formLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.RadioLRA2XYZ = QtGui.QRadioButton(self.groupBox_2)
        self.RadioLRA2XYZ.setObjectName(_fromUtf8("RadioLRA2XYZ"))
        self.verticalLayout_2.addWidget(self.RadioLRA2XYZ)
        self.RadioXYZ2LRA = QtGui.QRadioButton(self.groupBox_2)
        self.RadioXYZ2LRA.setObjectName(_fromUtf8("RadioXYZ2LRA"))
        self.verticalLayout_2.addWidget(self.RadioXYZ2LRA)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(65, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ConvertButton = QtGui.QPushButton(self.groupBox_2)
        self.ConvertButton.setMinimumSize(QtCore.QSize(100, 40))
        self.ConvertButton.setObjectName(_fromUtf8("ConvertButton"))
        self.horizontalLayout_2.addWidget(self.ConvertButton)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 360, 330, 381))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditProjectNo = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditProjectNo.setObjectName(_fromUtf8("lineEditProjectNo"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditProjectNo)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditRev = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditRev.setObjectName(_fromUtf8("lineEditRev"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditRev)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.textEditNotes = QtGui.QTextEdit(self.groupBox_3)
        self.textEditNotes.setObjectName(_fromUtf8("textEditNotes"))
        self.verticalLayout_3.addWidget(self.textEditNotes)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionImport_Data = QtGui.QAction(MainWindow)
        self.actionImport_Data.setObjectName(_fromUtf8("actionImport_Data"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExport_Data = QtGui.QAction(MainWindow)
        self.actionExport_Data.setObjectName(_fromUtf8("actionExport_Data"))
        self.actionGenerate_Report = QtGui.QAction(MainWindow)
        self.actionGenerate_Report.setObjectName(_fromUtf8("actionGenerate_Report"))
        self.actionGenerate_Report_2 = QtGui.QAction(MainWindow)
        self.actionGenerate_Report_2.setObjectName(_fromUtf8("actionGenerate_Report_2"))
        self.menuSave.addAction(self.actionNew)
        self.menuSave.addAction(self.actionImport_Data)
        self.menuSave.addAction(self.actionExport_Data)
        self.menuTools.addAction(self.actionGenerate_Report_2)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.XYZtable, self.LRAtable)
        MainWindow.setTabOrder(self.LRAtable, self.LineEditOuterDia)
        MainWindow.setTabOrder(self.LineEditOuterDia, self.LineEditWallThickness)
        MainWindow.setTabOrder(self.LineEditWallThickness, self.LineEditCLR)
        MainWindow.setTabOrder(self.LineEditCLR, self.LineEditLength)
        MainWindow.setTabOrder(self.LineEditLength, self.RadioLRA2XYZ)
        MainWindow.setTabOrder(self.RadioLRA2XYZ, self.RadioXYZ2LRA)
        MainWindow.setTabOrder(self.RadioXYZ2LRA, self.ConvertButton)

    def retranslateUi(self, MainWindow):
        item = self.XYZtable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.XYZtable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        item = self.XYZtable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        item = self.XYZtable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        item = self.LRAtable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.LRAtable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        item = self.LRAtable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        item = self.LRAtable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tube \\ Pipe data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Outer diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Wall thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "CLR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioLRA2XYZ.setText(QtGui.QApplication.translate("MainWindow", "LRA to XYZ", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioXYZ2LRA.setText(QtGui.QApplication.translate("MainWindow", "XYZ to LRA", None, QtGui.QApplication.UnicodeUTF8))
        self.ConvertButton.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Project Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Project number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Data.setText(QtGui.QApplication.translate("MainWindow", "Import Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Data.setText(QtGui.QApplication.translate("MainWindow", "Export Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Report.setText(QtGui.QApplication.translate("MainWindow", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Report_2.setText(QtGui.QApplication.translate("MainWindow", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))

